### ISSUE TITLE
network support

### ISSUE THREAD

**Issue by denisdemais** [dpapavas/luaprompt#14]
Hi,

how i can run this prompt from a network conecction (in C) ?

Thanks for any

**Comment by starius** [comment]
I don't understand the question. Can you give more details, please?

**Comment by denisdemais** [comment]
@starius  do you can make a example of "luaprompt network-enabled", i.e., lua telnet server-like.

thanks

**Comment by starius** [comment]
I see. It is not implemented. Probably you can implement it using luasocket and this module.

**Comment by dpapavas** [comment]
Can you please explain in more detail, what it is you're trying to do exactly?
