### ISSUE TITLE
Implicit definition of function "asprintf"

### ISSUE THREAD

**Issue by Nomadluap** [dpapavas/luaprompt#15]
```
luaprompt/prompt.c:305:29: warning: implicit declaration of function ‘asprintf’ [-Wimplicit-function-declaration]
                         l = asprintf (&candidate, "%d]", i);
                             ^~~~~~~~
```

This can be resolved by adding `#define _GNU_SOURCE` to the top of the file, but that may not be portable across compilers.

**Comment by dpapavas** [comment]
How are you building luaprompt?  Both the Makefile and the rockspec file specify the `_GNU_SOURCE` define, so that defining it at the top of the file shouldn't be necessary.  If you're compiling it into your own program, just add `-D_GNU_SOURCE` to the compilation command.

**Comment by Nomadluap** [comment]
Since I was using Cmake for my projects, I pulled the project sources into a custom cmake build file. 
My motivation behind creating this issue was to help others who may run into the same issue.

For those who are curious, my CMake file for the project can be found here: https://gist.github.com/Nomadluap/b10c2ba54ae371281fce2de988f49aae
