### ISSUE TITLE
"Could not find library file for HISTORY" on MacOS

### ISSUE THREAD

**Issue by bbugh** [dpapavas/luaprompt#17]
On Mac, with `readline` installed via `brew`, I was getting this:

```
Installing https://luarocks.org/luaprompt-0.7-1.src.rock...
Using https://luarocks.org/luaprompt-0.7-1.src.rock... switching to 'build' mode

Error: Could not find library file for HISTORY
  No file libhistory.a in /usr/lib
  No file libhistory.dylib in /usr/lib
  No file matching libhistory.so.* in /usr/lib
You may have to install HISTORY in your system and/or pass HISTORY_DIR or HISTORY_LIBDIR to the luarocks command.
Example: luarocks install luaprompt HISTORY_DIR=/usr/local
```

The fix was to force the link, which may have repercussions if anything else is using readline, which it doesn't seem to be on my system.

```
» brew link readline
Warning: readline is keg-only and must be linked with --force
Note that doing so can interfere with building software.

» brew link --force readline
Linking /usr/local/Cellar/readline/7.0.3_1... 17 symlinks created
```

Might be helpful to put this in the README for Mac.

**Comment by dpapavas** [comment]
Thanks for the report.  It's weird that, although I've had building problems on OSX reported before, this hasn't come up.  Anyway, I bet anyone having the same problem and searching for a solution based on the error messages, will be more likely to find this issue, rather than read through the whole README, so I'll just leave it here.

**Comment by faudebert** [comment]
If this might help someone, note I was able to install `luaprompt` without using `brew link --force readline` like this:

```sh
$ luarocks install luaprompt HISTORY_DIR=/usr/local/Cellar/readline/8.0.4 \
    READLINE_DIR=/usr/local/Cellar/readline/8.0.4
Installing https://luarocks.org/luaprompt-0.7-1.src.rock
...
```

**Comment by paines** [comment]
It seem to be getting more and more complicated. M1 with Monterey 12.3.1

```
$ luarocks install readline HISTORY_INCDIR=/opt/homebrew/Cellar/readline/8.1.2/include/  \
 HISTORY_LIBDIR=/opt/homebrew/Cellar/readline/8.1.2/lib/ READLINE_DIR=/opt/homebrew/Cellar/readline/8.1.2/
```

**Comment by camhine** [comment]
Thanks @paines.

I thought I was successfully installing the readline module with the command:

```
$ luarocks install readline HISTORY_DIR=/opt/homebrew/opt/readline
```

But actually requiring the module lead to an error:

```
luarocks readline error loading module 'C-readline'
```

I found your suggestion and modified it so that it's not tied to a specific version:

```
$ luarocks install readline HISTORY_INCDIR=/opt/homebrew/opt/readline/include/ \
HISTORY_LIBDIR=/opt/homebrew/opt/readline/lib/ READLINE_DIR=/opt/homebrew/opt/readline/
``` 

Now I have a working readline module 🎉.
