### ISSUE TITLE
Not escape Unicode character like lua

### ISSUE THREAD

**Issue by Freed-Wu** [dpapavas/luaprompt#21]
In lua:

```
$ lua
> "MSPY雙拼"
MSPY雙拼
```

In luap:

```
$ luap
$ "MSPY雙拼"
_[1] = "MSPY\233\155\153\230\139\188"
```

Can luap not escape Unicode character like lua?

**Comment by dpapavas** [comment]
It looks like the lua interpreter just uses the standard Lua `print` function to print strings, which in turn just writes them to standard output.  I implmeneted an `ESCAPE_STRINGS` configuration macro which is enabled by default to provide the current behavior. If disabled, it matches the behavior of `lua`.

So with `ESCAPE_STRINGS`:
```
$ luap
Lua 5.4.4  Copyright (C) 1994-2022 Lua.org, PUC-Rio
luap 0.8 Copyright (C) 2012-2023 Dimitris Papavasiliou, Boris Nagaev
>  'φοο\t'
_[1] = "\207\134\206\191\206\191\t"
```

Without it:
```
$ luap
Lua 5.4.4  Copyright (C) 1994-2022 Lua.org, PUC-Rio
luap 0.8 Copyright (C) 2012-2023 Dimitris Papavasiliou, Boris Nagaev
>  'φοο\t'
_[1] = "φοο	"
```

Would that work for you?

**Comment by Freed-Wu** [comment]
LGTM！

**Comment by dpapavas** [comment]
I've pushed version 0.9 and  uploaded a new rock to [LuaRocks](https://luarocks.org/modules/dpapavas/luaprompt).  To get your desired behavior you'll need to install a custom rock (or simply a  manually built version of the code) where the `ESCAPE_STRINGS` configuration macro is not set in the `Makefile`.

**Comment by Freed-Wu** [comment]
1. By default, it is not escaped, which is not convenient. How about enable escape_strings by default?
2. Can we control escape_strings by config? such as:

```lua
require'prompt'.escape =  true
```

**Comment by dpapavas** [comment]
Sorry, I missed this entirely.  Please see comment in the PR you opened.
