### ISSUE TITLE
segfault if included file tries to index nil

### ISSUE THREAD

**Issue by starius** [dpapavas/luaprompt#4]
Hello,

I am using luaprompt 0.3.1.

Test for this bug:
```bash
$ cat testl.lua
A = B.C
$ luap -i test.lua
Segmentation fault
$ lua -i test.lua 
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
lua: test.lua:1: attempt to index global 'B' (a nil value)
stack traceback:
        test.lua:1: in main chunk
        [C]: ?
```

I have not tested this bug in newer versions of luaprompt.

**Comment by dpapavas** [comment]
Hi, and thanks for the report.  This bug affects all versions.  I've made a fix in commit 997bac8e31bb302acb3567fd6ed4449677bfcc33.  If you can't switch to 0.5 just apply the patch to 0.3.1 manually.  It's just a one-liner.
