### ISSUE TITLE
if luap_setprompts called, then prompts are colored even if luap_setcolor(false) called

### ISSUE THREAD

**Issue by starius** [dpapavas/luaprompt#7]
I have disabled colors and set custom prompts ('%' and '%%'). As a result, all text produced is not colored, except prompts:

![Luaprompt session](https://i.imgur.com/pgaifLn.png)

**Comment by dpapavas** [comment]
You're right.  I only set the color and prompts in a specific order in luap, so this bug never turned up.  It's should be fixed in the wip branch.

**Comment by starius** [comment]
The problem is not fixed in wip branch.

**Comment by dpapavas** [comment]
I'm fairly sure that it is.  You can try the following in the wip branch:

```
dimitris@debian:~/sandbox/luaprompt$ make prompt.so 
cc -o prompt.so -shared -fpic -g -Wall -Wextra -Wno-unused-parameter -I.. -DHAVE_ASPRINTF -DHAVE_LIBREADLINE -DHAVE_READLINE_READLINE_H -DHAVE_READLINE_HISTORY -DHAVE_READLINE_HISTORY_H -D_GNU_SOURCE -DCOMPLETE_KEYWORDS	 -DCOMPLETE_MODULES      -DCOMPLETE_TABLE_KEYS	 -DCOMPLETE_METATABLE_KEYS  -DCOMPLETE_FILE_NAMES	 `pkg-config --cflags lua5.2` module.c prompt.c -lreadline -lhistory `pkg-config --libs lua5.2`
dimitris@debian:~/sandbox/luaprompt$ lua -lprompt
Lua 5.2.1  Copyright (C) 1994-2012 Lua.org, PUC-Rio
> prompt.prompts = {"%  ", "%% "}
> prompt.colorize = false
> prompt.enter()
%  
```
The prompts should be uncolored.  They are for me.

**Comment by starius** [comment]
It works.

Btw, loading with `lua -lprompt` to global variable doesn't work in Lua 5.1:
```
$ lua5.1 -lprompt
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
> prompt.prompts = {"%  ", "%% "}
stdin:1: attempt to index global 'prompt' (a nil value)
stack traceback:
        stdin:1: in main chunk
        [C]: ?
> =prompt
nil
```

**Comment by dpapavas** [comment]
> Btw, loading with lua -lprompt to global variable doesn't work in Lua 5.1:

Well, if I understand [this](http://lua-users.org/wiki/ModulesTutorial) correctly, the "modern" way of writing modules is without polluting the globals table.  That is require should just return the module table so than one can write

    prompt = require "prompt"

instead of just

    require "prompt"

In luap I explicitly create a global variable for modules loaded with the -l switch.  Shouldn't the default Lua interpreter be doing the same?  Am I missing somthing?

**Comment by starius** [comment]
> Shouldn't the default Lua interpreter be doing the same?

Called with `-l`, Lua 5.1 standalone [only requires a module][1], but Lua >= 5.2 standalone [assigns it to a global variable][2] as well. I don't know why. This "feature" doesn't seem to be documented in [the manual][3].

[1]: http://www.lua.org/source/5.1/lua.c.html#dolibrary
[2]: http://www.lua.org/source/5.2/lua.c.html#dolibrary
[3]: http://www.lua.org/manual/5.2/manual.html#7

**Comment by dpapavas** [comment]
Well, I've made it so that the module does export a global variable if version == 5.1 and also, so that luap does not export one when loading libraries through -l in that case.  Best to match the expected behavior I suppose, even if it is confusing.
